/// <autosync enabled="true" />
/// <reference path="../databas json/js/jquery.columns.min.js" />
/// <reference path="../databas json/js/jquery.min.js" />
/// <reference path="../databas json/js/mustache.min.js" />
/// <reference path="../databas json/js/result.js" />
/// <reference path="../databas json/js/tabellajaxs.js" />
/// <reference path="../databas json/js/tabellajaxt.js" />
/// <reference path="../databas json/plugins/ajaxpaging.js" />
/// <reference path="../databas json/plugins/gotopage.js" />
/// <reference path="../js/controller.js" />
/// <reference path="../js/jquery.js" />
/// <reference path="../js/result.js" />
/// <reference path="../old/localdata.js" />
/// <reference path="../old/prov.js" />
/// <reference path="bootstrap.js" />
/// <reference path="jquery-1.9.1.js" />
